# Package Overview
package_name: lstm_model

# Data Files
data_file: EURUSD_Candlestick_1_h_ASK_31.12.2011-31.01.2023.csv

# Variables.
pipeline_name: LSTM_pipe

usecols: ['Gmt time','Close'])

features:
  - Gmt time # In file
  - Close # In file
  - fecha # Created
  - precio_EURUSD # Created
  - target # Created
  # this one is only to calculate temporal variable:
  #- YrSold

# Dates to split the serie: minimun date and train test split date.
corte_fecha: 201212
corte_train_test: 202208

# Size of the LSTM window. Number of historical records to predict the next value
ventana: 120 #10 días
# Number of predictors.
n_features: 1
# Epochs of LSTM.
epochs: 100
